version: '3.4'

services:
    parse:
        image: netreconlab/parse-hipaa:latest
        environment:
            CLUSTER_INSTANCES: 4
            PARSE_SERVER_APPLICATION_ID: E036A0C5-6829-4B40-9B3B-3E05F6DF32B2
            PARSE_SERVER_PRIMARY_KEY: E2466756-93CF-4C05-BA44-FF5D9C34E99F
            PARSE_SERVER_READ_ONLY_PRIMARY_KEY: 367F7395-2E3A-46B1-ABA3-963A25D533C3
            PARSE_SERVER_WEBHOOK_KEY: 553D229E-64DF-4928-99F5-B71CCA94A44A
            PARSE_SERVER_ENCRYPTION_KEY: 72F8F23D-FDDB-4792-94AE-72897F0688F9
            PARSE_SERVER_OBJECT_ID_SIZE: 32
            PARSE_SERVER_DATABASE_URI: mongodb://${MONGO_PARSE_USER}:${MONGO_PARSE_PASSWORD}@db:27017/${MONGO_PARSE_DB}
            PORT: ${PORT}
            PARSE_SERVER_MOUNT_PATH: ${MOUNT_PATH}
            PARSE_SERVER_URL: http://parse:${PORT}${MOUNT_PATH}
            PARSE_PUBLIC_SERVER_URL: http://localhost:${PORT}${MOUNT_PATH}
            PARSE_SERVER_CLOUD: /parse-server/cloud/main.js
            PARSE_SERVER_MOUNT_GRAPHQL: 'true'
            PARSE_SERVER_ALLOW_CLIENT_CLASS_CREATION: 'false' # Don't allow classes to be created on the client side. You can create classes by using ParseDashboard instead
            PARSE_SERVER_ALLOW_CUSTOM_OBJECTID: 'true' # Required to be true for ParseCareKit
            PARSE_SERVER_ENABLE_SCHEMA_HOOKS: 'true'
            PARSE_SERVER_DIRECT_ACCESS: 'false' # WARNING: Setting to 'true' is known to cause crashes on parse-hipaa running postgres
            PARSE_SERVER_ENABLE_PRIVATE_USERS: 'true'
            PARSE_SERVER_USING_PARSECAREKIT: 'true' # If you are not using ParseCareKit, set this to 'false'
            PARSE_VERBOSE: 'false'
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./parse/index.js:/parse-server/index.js
            - ./parse/cloud:/parse-server/cloud
        restart: always
        depends_on:
            - db
        command: ["node", "index.js"]
    dashboard:
        image: parseplatform/parse-dashboard:latest
        environment:
            PARSE_DASHBOARD_TRUST_PROXY: 1
            PARSE_DASHBOARD_COOKIE_SESSION_SECRET: AB8849B6-D725-4A75-AA73-AB7103F0363F # This should be constant across all deployments on your system
            MOUNT_PATH: /dashboard # This needs to be exactly what you plan it to be behind the proxy, i.e. If you want to access cs.uky.edu/dashboard it should be "/dashboard"
        command: parse-dashboard --dev
        volumes:
            - ./dashboard/parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json
        ports:
            - 127.0.0.1:4040:4040
        depends_on:
            - parse
    db:
        image: netreconlab/hipaa-mongo:4.4
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_PARSE_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PARSE_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_PARSE_DB}
        restart: always
        ports:
            - 27017:27017
        # Uncomment volumes below to persist postgres data. Make sure to change directory to store data locally
        #volumes:
        #  - /My/Encrypted/Drive/db:/data/db
        #  - /My/Encrypted/Drive/log/:/mongologs
    scan:
        image: netreconlab/clamscan:latest
        restart: always
