FROM ubuntu:trusty

RUN apt-get update && apt-get install -yq curl && apt-get clean

WORKDIR /app

#ADD test.sh wait-for-parse.sh /app/

CMD ["./wait-for-parse.sh", "db", "bash", "test.sh"]

#["bash", "test.sh"]
