version: "2.0"

instances:
    parse:
        image: netreconlab/parse-hipaa:latest
        ports:
            - 1337:1337
        volumes:
            - ./scripts/wait-for-postgres.sh:/parse-server/wait-for-postgres.sh
            - ./parse/index.js:/parse-server/index.js
            - ./parse/cloud:/parse-server/cloud
            - ./files:/parse-server/files # All files uploaded from users are stored to an ecrypted drive locally for HIPAA compliance
        #restart: always
        start:
            - fakeroot
        exec:
            options:
                - "env-file=general.env"
            command: ./wait-for-postgres.sh db node index.js
        depends_on:
            - db
    dashboard:
        image: parseplatform/parse-dashboard:latest
        start:
            - fakeroot
        exec:
            options:
                - "env-file=dashboard.env"
            command: parse-dashboard --dev
        volumes:
            - ./dashboard/parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json
        ports:
            - 4040:4040
        depends_on:
            - parse
    db:
        image: netreconlab/hipaa-postgres:latest
        #restart: always
        ports:
            - 5432:5432
        start:
            - fakeroot
        exec:
            options:
                - "env-file=general.env"
            command: postgres -c shared_preload_libraries=pgaudit
        # Uncomment volumes below to persist postgres data. Make sure to change directory to store data locally
   #     volumes:
   #         - /My/Encrypted/Drive/data:/var/lib/postgresql/data #Mount your own drive
   #         - /My/Encrypted/Drive/archivedir:/var/lib/postgresql/archivedir #Mount your own drive
   # scan:
   #     image: netreconlab/clamscan:latest
   #     restart: always
